.TH "Player.h" 3 "Blackjack_1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player.h \- Base player class and derived player types for blackjack\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br
\fR#include <vector>\fP
.br
\fR#include 'Card\&.h'\fP
.br
\fR#include 'PlayerStats\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlayer\fP"
.br
.RI "Abstract base class for blackjack players Defines common functionality for managing hands, bets, funds and statistics\&. "
.ti -1c
.RI "class \fBHuman\fP"
.br
.RI "\fBHuman\fP player class Implements interactive player decisions\&. "
.ti -1c
.RI "class \fBDealer\fP"
.br
.RI "\fBDealer\fP class Implements dealer-specific logic and display\&. "
.in -1c
.SH "Detailed Description"
.PP 
Base player class and derived player types for blackjack\&. 


.PP
\fBAuthor\fP
.RS 4
Ireoluwa Dairo 
.RE
.PP
\fBDate\fP
.RS 4
2024-11-27 
.RE
.PP

.PP
Definition in file \fBPlayer\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Blackjack_1 from the source code\&.
