.TH "BlackJackGame.h" 3 "Blackjack_1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlackJackGame.h \- Main game controller class for Blackjack card game\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'Deck\&.h'\fP
.br
\fR#include 'Player\&.h'\fP
.br
\fR#include 'SaveGame\&.h'\fP
.br
\fR#include <memory>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGame\fP"
.br
.RI "Main controller class implementing Blackjack game logic\&. "
.in -1c
.SH "Detailed Description"
.PP 
Main game controller class for Blackjack card game\&. 


.PP
\fBAuthor\fP
.RS 4
Ireoluwa Dairo 
.RE
.PP
\fBDate\fP
.RS 4
2024-11-27 
.RE
.PP

.PP
Definition in file \fBBlackJackGame\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Blackjack_1 from the source code\&.
