.TH "Card.cpp" 3 "Blackjack_1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Card.cpp \- Implementation of \fBCard\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'Card\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &os, const \fBCard\fP &card)"
.br
.RI "Stream output operator\&. "
.in -1c
.SH "Detailed Description"
.PP 
Implementation of \fBCard\fP class\&. 


.PP
\fBAuthor\fP
.RS 4
Ireoluwa Dairo 
.RE
.PP
\fBDate\fP
.RS 4
2024-11-27 
.RE
.PP

.PP
Definition in file \fBCard\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "ostream & operator<< (ostream & os, const \fBCard\fP & card)"

.PP
Stream output operator\&. 
.PP
\fBParameters\fP
.RS 4
\fIos\fP Output stream 
.br
\fIcard\fP \fBCard\fP to output 
.RE
.PP
\fBReturns\fP
.RS 4
ostream& Reference to output stream 
.RE
.PP

.PP
Definition at line \fB135\fP of file \fBCard\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Blackjack_1 from the source code\&.
