.TH "Card.h" 3 "Blackjack_1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Card.h \- Playing card class implementation\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br
\fR#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCard\fP"
.br
.RI "Represents a single playing card in a standard deck\&. "
.in -1c
.SH "Detailed Description"
.PP 
Playing card class implementation\&. 


.PP
\fBAuthor\fP
.RS 4
Ireoluwa Dairo 
.RE
.PP
\fBDate\fP
.RS 4
2024-11-27 
.RE
.PP

.PP
Definition in file \fBCard\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Blackjack_1 from the source code\&.
