.TH "Card" 3 "Blackjack_1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Card \- Represents a single playing card in a standard deck\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Card\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum class \fBSuit\fP { \fBHEARTS\fP, \fBDIAMONDS\fP, \fBCLUBS\fP, \fBSPADES\fP }"
.br
.RI "Enumeration of card suits\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCard\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "\fBCard\fP (int value, \fBSuit\fP suit)"
.br
.RI "Constructor with value and suit\&. "
.ti -1c
.RI "\fBCard\fP (const \fBCard\fP &other)"
.br
.RI "Copy constructor\&. "
.ti -1c
.RI "\fB~Card\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "int \fBgetValue\fP () const"
.br
.RI "Get card's numeric value\&. "
.ti -1c
.RI "\fBSuit\fP \fBgetSuit\fP () const"
.br
.RI "Get card's suit\&. "
.ti -1c
.RI "std::string \fBgetSuitString\fP () const"
.br
.RI "Get string representation of card's suit\&. "
.ti -1c
.RI "std::string \fBgetValueString\fP () const"
.br
.RI "Get string representation of card's value\&. "
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCard\fP &other) const"
.br
.RI "Equality comparison operator\&. "
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBCard\fP &other) const"
.br
.RI "Inequality comparison operator\&. "
.ti -1c
.RI "\fBCard\fP & \fBoperator=\fP (const \fBCard\fP &other)"
.br
.RI "Assignment operator\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBgetNumCardsCreated\fP ()"
.br
.RI "Get total number of \fBCard\fP objects created\&. "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBCard\fP &card)"
.br
.RI "Stream output operator\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a single playing card in a standard deck\&. 

This class implements a playing card with a value (1-13) and suit\&. It includes functionality for comparing cards, converting to string representations, and tracking the total number of cards created\&. 
.PP
Definition at line \fB22\fP of file \fBCard\&.h\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum class \fBCard::Suit\fP\fR [strong]\fP"

.PP
Enumeration of card suits\&. Uses enum class for type safety and scoping 
.PP
Definition at line \fB29\fP of file \fBCard\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Card::Card ()"

.PP
Default constructor\&. Default constructor Creates Ace of Hearts by default\&. 
.PP
Definition at line \fB19\fP of file \fBCard\&.cpp\fP\&.
.SS "Card::Card (int value, \fBSuit\fP suit)"

.PP
Constructor with value and suit\&. Parameterized constructor\&.

.PP
\fBParameters\fP
.RS 4
\fIvalue\fP \fBCard\fP's numeric value (1-13) 
.br
\fIsuit\fP \fBCard\fP's suit 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIstd::invalid_argument\fP if value is outside valid range
.RE
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP \fBCard\fP value (1-13) 
.br
\fIsuit\fP \fBCard\fP suit 
.RE
.PP

.PP
Definition at line \fB28\fP of file \fBCard\&.cpp\fP\&.
.SS "Card::Card (const \fBCard\fP & other)"

.PP
Copy constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIother\fP \fBCard\fP to copy from 
.RE
.PP

.PP
Definition at line \fB38\fP of file \fBCard\&.cpp\fP\&.
.SS "Card::~Card ()"

.PP
Destructor\&. Destructor Decrements card count\&. 
.PP
Definition at line \fB46\fP of file \fBCard\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int Card::getNumCardsCreated ()\fR [static]\fP"

.PP
Get total number of \fBCard\fP objects created\&. 
.PP
\fBReturns\fP
.RS 4
int Number of cards created

.PP
int Number of cards currently in existence 
.RE
.PP

.PP
Definition at line \fB125\fP of file \fBCard\&.cpp\fP\&.
.SS "\fBCard::Suit\fP Card::getSuit () const\fR [inline]\fP"

.PP
Get card's suit\&. 
.PP
\fBReturns\fP
.RS 4
Suit Enumerated suit value 
.RE
.PP

.PP
Definition at line \fB129\fP of file \fBCard\&.h\fP\&.
.SS "string Card::getSuitString () const"

.PP
Get string representation of card's suit\&. Get string representation of card suit\&.

.PP
\fBReturns\fP
.RS 4
std::string Suit name as string

.PP
string Name of suit 
.RE
.PP

.PP
Definition at line \fB66\fP of file \fBCard\&.cpp\fP\&.
.SS "int Card::getValue () const\fR [inline]\fP"

.PP
Get card's numeric value\&. 
.PP
\fBReturns\fP
.RS 4
int Value between 1-13 
.RE
.PP

.PP
Definition at line \fB128\fP of file \fBCard\&.h\fP\&.
.SS "string Card::getValueString () const"

.PP
Get string representation of card's value\&. Get string representation of card value\&.

.PP
\fBReturns\fP
.RS 4
std::string \fBCard\fP value as string (e\&.g\&., 'Ace', 'King', etc\&.)

.PP
string \fBCard\fP value or face card name 
.RE
.PP

.PP
Definition at line \fB80\fP of file \fBCard\&.cpp\fP\&.
.SS "bool Card::operator!= (const \fBCard\fP & other) const"

.PP
Inequality comparison operator\&. 
.PP
\fBParameters\fP
.RS 4
\fIother\fP \fBCard\fP to compare with 
.RE
.PP
\fBReturns\fP
.RS 4
bool True if cards differ in value or suit 
.RE
.PP

.PP
Definition at line \fB104\fP of file \fBCard\&.cpp\fP\&.
.SS "\fBCard\fP & Card::operator= (const \fBCard\fP & other)"

.PP
Assignment operator\&. 
.PP
\fBParameters\fP
.RS 4
\fIother\fP \fBCard\fP to assign from 
.RE
.PP
\fBReturns\fP
.RS 4
\fBCard\fP& Reference to this card 
.RE
.PP

.PP
Definition at line \fB113\fP of file \fBCard\&.cpp\fP\&.
.SS "bool Card::operator== (const \fBCard\fP & other) const"

.PP
Equality comparison operator\&. 
.PP
\fBParameters\fP
.RS 4
\fIother\fP \fBCard\fP to compare with 
.RE
.PP
\fBReturns\fP
.RS 4
bool True if cards have same value and suit
.RE
.PP
\fBParameters\fP
.RS 4
\fIother\fP \fBCard\fP to compare with 
.RE
.PP
\fBReturns\fP
.RS 4
bool True if cards match in value and suit 
.RE
.PP

.PP
Definition at line \fB95\fP of file \fBCard\&.cpp\fP\&.
.SH "Friends And Related Symbol Documentation"
.PP 
.SS "std::ostream & operator<< (std::ostream & os, const \fBCard\fP & card)\fR [friend]\fP"

.PP
Stream output operator\&. 
.PP
\fBParameters\fP
.RS 4
\fIos\fP Output stream 
.br
\fIcard\fP \fBCard\fP to output 
.RE
.PP
\fBReturns\fP
.RS 4
std::ostream& Reference to output stream 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Blackjack_1 from the source code\&.
