.TH "Game" 3 "Blackjack_1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game \- Main controller class implementing Blackjack game logic\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <BlackJackGame\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBstart\fP ()"
.br
.RI "Starts a new game session\&. "
.ti -1c
.RI "\fBGame\fP (const \fBGame\fP &)=delete"
.br
.ti -1c
.RI "\fBGame\fP & \fBoperator=\fP (const \fBGame\fP &)=delete"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBGame\fP & \fBget\fP ()"
.br
.RI "Get the single instance of the \fBGame\fP class\&. "
.in -1c
.SH "Detailed Description"
.PP 
Main controller class implementing Blackjack game logic\&. 

This class implements the Singleton pattern and manages the complete lifecycle of a Blackjack game including player turns, dealer actions, betting, and game state persistence\&. 
.PP
Definition at line \fB26\fP of file \fBBlackJackGame\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBGame\fP & Game::get ()\fR [static]\fP"

.PP
Get the single instance of the \fBGame\fP class\&. Get single instance of \fBGame\fP\&.

.PP
\fBReturns\fP
.RS 4
\fBGame\fP& Reference to the singleton game instance

.PP
\fBGame\fP& Reference to game instance
.RE
.PP
Creates instance if it doesn't exist 
.PP
Definition at line \fB21\fP of file \fBBlackJackGame\&.cpp\fP\&.
.SS "void Game::start ()"

.PP
Starts a new game session\&. Start game session Initializes, runs main loop, and saves on exit\&.

.PP
Initializes game components and begins the main game loop\&. 
.PP
Definition at line \fB50\fP of file \fBBlackJackGame\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Blackjack_1 from the source code\&.
