.TH "GameRes" 3 "Blackjack_1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameRes \- Represents the result of a single game Stores win/loss status and amount won/lost\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <PlayerStats\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBgetAmt\fP () const"
.br
.RI "Get amount won/lost\&. "
.ti -1c
.RI "bool \fBisWin\fP () const"
.br
.RI "Check if game was won\&. "
.ti -1c
.RI "\fBGameRes\fP (bool win=false, int amt=0)"
.br
.RI "Constructor\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents the result of a single game Stores win/loss status and amount won/lost\&. 
.PP
Definition at line \fB19\fP of file \fBPlayerStats\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GameRes::GameRes (bool win = \fRfalse\fP, int amt = \fR0\fP)\fR [inline]\fP"

.PP
Constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIwin\fP Whether game was won 
.br
\fIamt\fP Amount won/lost 
.RE
.PP

.PP
Definition at line \fB38\fP of file \fBPlayerStats\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int GameRes::getAmt () const\fR [inline]\fP"

.PP
Get amount won/lost\&. 
.PP
\fBReturns\fP
.RS 4
int Amount from game result 
.RE
.PP

.PP
Definition at line \fB25\fP of file \fBPlayerStats\&.h\fP\&.
.SS "bool GameRes::isWin () const\fR [inline]\fP"

.PP
Check if game was won\&. 
.PP
\fBReturns\fP
.RS 4
bool True if game was won 
.RE
.PP

.PP
Definition at line \fB31\fP of file \fBPlayerStats\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Blackjack_1 from the source code\&.
