.TH "main.cpp" 3 "Blackjack_1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp \- Main entry point for Blackjack game\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <cstdlib>\fP
.br
\fR#include 'BlackjackGame\&.h'\fP
.br
\fR#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBrunBlackjackTest\fP ()"
.br
.RI "Test function demonstrating friend functionality and exception handling\&. "
.ti -1c
.RI "int \fBmain\fP ()"
.br
.RI "Main program entry point\&. "
.in -1c
.SH "Detailed Description"
.PP 
Main entry point for Blackjack game\&. 


.PP
\fBAuthor\fP
.RS 4
Ireoluwa Dairo 
.RE
.PP
\fBDate\fP
.RS 4
2024-11-27 
.RE
.PP

.PP
Definition in file \fBmain\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Main program entry point\&. 
.PP
\fBReturns\fP
.RS 4
int Exit status (0 for success, 1 for error) 
.RE
.PP

.PP
Definition at line \fB31\fP of file \fBmain\&.cpp\fP\&.
.SS "void runBlackjackTest ()"

.PP
Test function demonstrating friend functionality and exception handling\&. Creates a game instance and runs a test session 
.PP
Definition at line \fB17\fP of file \fBmain\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Blackjack_1 from the source code\&.
