.TH "Player.cpp" 3 "Blackjack_1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player.cpp \- Implementation of \fBPlayer\fP base class and derived Human/Dealer classes\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'Player\&.h'\fP
.br
\fR#include <iostream>\fP
.br

.SH "Detailed Description"
.PP 
Implementation of \fBPlayer\fP base class and derived Human/Dealer classes\&. 


.PP
\fBAuthor\fP
.RS 4
Ireoluwa Dairo 
.RE
.PP
\fBDate\fP
.RS 4
2024-11-27 
.RE
.PP

.PP
Definition in file \fBPlayer\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Blackjack_1 from the source code\&.
