.TH "PStats" 3 "Blackjack_1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PStats \- \fBPlayer\fP statistics manager Tracks game results and calculates statistics\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <PlayerStats\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPStats\fP (int max=100)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fBPStats\fP (const \fBPStats\fP &other)"
.br
.RI "Copy constructor\&. "
.ti -1c
.RI "\fB~PStats\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "\fBPStats\fP & \fBoperator=\fP (const \fBPStats\fP &rhs)"
.br
.RI "Assignment operator\&. "
.ti -1c
.RI "\fBPStats\fP \fBoperator+\fP (const \fBPStats\fP &rhs) const"
.br
.RI "Addition operator\&. "
.ti -1c
.RI "bool \fBoperator<\fP (const \fBPStats\fP &rhs) const"
.br
.RI "Less than operator\&. "
.ti -1c
.RI "void \fBadd\fP (const \fBGameRes\fP &res)"
.br
.RI "Add game result\&. "
.ti -1c
.RI "int \fBgetRate\fP () const"
.br
.RI "Get win rate percentage\&. "
.ti -1c
.RI "void \fBsetAll\fP (int games, int wins)"
.br
.RI "Set total games and wins\&. "
.ti -1c
.RI "\fBStats\fP \fBgetAll\fP () const"
.br
.RI "Get all statistics\&. "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "void \fBshowAll\fP (const \fBPStats\fP &st)"
.br
.RI "Friend function to display all statistics\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBPlayer\fP statistics manager Tracks game results and calculates statistics\&. 
.PP
Definition at line \fB59\fP of file \fBPlayerStats\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PStats::PStats (int maxSz = \fR100\fP)"

.PP
Constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fImax\fP Maximum number of results to store
.br
\fImaxSz\fP Maximum number of game results to store 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIruntime_error\fP if memory allocation fails 
.RE
.PP

.PP
Definition at line \fB19\fP of file \fBPlayerStats\&.cpp\fP\&.
.SS "PStats::PStats (const \fBPStats\fP & old)"

.PP
Copy constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIother\fP \fBPStats\fP to copy from
.br
\fIold\fP \fBPStats\fP object to copy from 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIruntime_error\fP if memory allocation fails 
.RE
.PP

.PP
Definition at line \fB38\fP of file \fBPlayerStats\&.cpp\fP\&.
.SS "PStats::~PStats ()"

.PP
Destructor\&. Destructor Frees allocated memory and decrements counter\&. 
.PP
Definition at line \fB60\fP of file \fBPlayerStats\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PStats::add (const \fBGameRes\fP & newRes)"

.PP
Add game result\&. Add new game result\&.

.PP
\fBParameters\fP
.RS 4
\fIres\fP Result to add
.br
\fInewRes\fP \fBGame\fP result to add 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIruntime_error\fP if results array is full 
.RE
.PP

.PP
Definition at line \fB120\fP of file \fBPlayerStats\&.cpp\fP\&.
.SS "\fBStats\fP PStats::getAll () const"

.PP
Get all statistics\&. Get games and wins stats\&.

.PP
\fBReturns\fP
.RS 4
\fBStats\fP Structure with games and wins

.PP
\fBStats\fP Structure containing games and wins 
.RE
.PP

.PP
Definition at line \fB111\fP of file \fBPlayerStats\&.cpp\fP\&.
.SS "int PStats::getRate () const"

.PP
Get win rate percentage\&. 
.PP
\fBReturns\fP
.RS 4
int Win rate as percentage 
.RE
.PP

.PP
Definition at line \fB140\fP of file \fBPlayerStats\&.cpp\fP\&.
.SS "\fBPStats\fP PStats::operator+ (const \fBPStats\fP & rhs) const"

.PP
Addition operator\&. 
.PP
\fBParameters\fP
.RS 4
\fIrhs\fP \fBPStats\fP to add 
.RE
.PP
\fBReturns\fP
.RS 4
\fBPStats\fP Combined statistics 
.RE
.PP

.PP
Definition at line \fB158\fP of file \fBPlayerStats\&.cpp\fP\&.
.SS "bool PStats::operator< (const \fBPStats\fP & rhs) const"

.PP
Less than operator\&. Less than comparison operator\&.

.PP
\fBParameters\fP
.RS 4
\fIrhs\fP \fBPStats\fP to compare with 
.RE
.PP
\fBReturns\fP
.RS 4
bool True if this win rate is less than rhs 
.RE
.PP

.PP
Definition at line \fB149\fP of file \fBPlayerStats\&.cpp\fP\&.
.SS "\fBPStats\fP & PStats::operator= (const \fBPStats\fP & rhs)"

.PP
Assignment operator\&. 
.PP
\fBParameters\fP
.RS 4
\fIrhs\fP \fBPStats\fP to assign from 
.RE
.PP
\fBReturns\fP
.RS 4
\fBPStats\fP& Reference to this object
.RE
.PP
\fBParameters\fP
.RS 4
\fIrhs\fP \fBPStats\fP to assign from 
.RE
.PP
\fBReturns\fP
.RS 4
\fBPStats\fP& Reference to this object 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIruntime_error\fP if memory allocation fails 
.RE
.PP

.PP
Definition at line \fB71\fP of file \fBPlayerStats\&.cpp\fP\&.
.SS "void PStats::setAll (int gms, int wns)"

.PP
Set total games and wins\&. 
.PP
\fBParameters\fP
.RS 4
\fIgames\fP Total games 
.br
\fIwins\fP Total wins
.br
\fIgms\fP Total games 
.br
\fIwns\fP Total wins 
.RE
.PP

.PP
Definition at line \fB97\fP of file \fBPlayerStats\&.cpp\fP\&.
.SH "Friends And Related Symbol Documentation"
.PP 
.SS "void showAll (const \fBPStats\fP & st)\fR [friend]\fP"

.PP
Friend function to display all statistics\&. 
.PP
\fBParameters\fP
.RS 4
\fIst\fP \fBPStats\fP to display 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Blackjack_1 from the source code\&.
