.TH "Save" 3 "Blackjack_1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Save \- Structure containing saveable game state data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SaveGame\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBname\fP [30]"
.br
.ti -1c
.RI "int \fBfunds\fP"
.br
.ti -1c
.RI "int \fBwins\fP"
.br
.ti -1c
.RI "int \fBgames\fP"
.br
.ti -1c
.RI "int \fBgmsAll\fP"
.br
.ti -1c
.RI "int \fBwinsAll\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure containing saveable game state data\&. 
.PP
Definition at line \fB19\fP of file \fBSaveGame\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Save::funds"
Current funds 
.PP
Definition at line \fB21\fP of file \fBSaveGame\&.h\fP\&.
.SS "int Save::games"
Current session games 
.PP
Definition at line \fB23\fP of file \fBSaveGame\&.h\fP\&.
.SS "int Save::gmsAll"
Total games played 
.PP
Definition at line \fB24\fP of file \fBSaveGame\&.h\fP\&.
.SS "char Save::name[30]"
\fBPlayer\fP name 
.PP
Definition at line \fB20\fP of file \fBSaveGame\&.h\fP\&.
.SS "int Save::wins"
Current session wins 
.PP
Definition at line \fB22\fP of file \fBSaveGame\&.h\fP\&.
.SS "int Save::winsAll"
Total games won 
.PP
Definition at line \fB25\fP of file \fBSaveGame\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Blackjack_1 from the source code\&.
