.TH "SaveGame" 3 "Blackjack_1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SaveGame \- Static class for managing game state persistence\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SaveGame\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBload\fP (\fBSave\fP &data, const string &user)"
.br
.RI "Load saved game data\&. "
.ti -1c
.RI "static bool \fBsave\fP (const \fBSave\fP &data, const string &user)"
.br
.RI "\fBSave\fP current game data\&. "
.ti -1c
.RI "static bool \fBvalid\fP (const string &user)"
.br
.RI "Check if save data exists for user\&. "
.in -1c
.SH "Detailed Description"
.PP 
Static class for managing game state persistence\&. 
.PP
Definition at line \fB32\fP of file \fBSaveGame\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool SaveGame::load (\fBSave\fP & data, const string & user)\fR [static]\fP"

.PP
Load saved game data\&. Load saved game data for user\&.

.PP
\fBParameters\fP
.RS 4
\fIdata\fP \fBSave\fP structure to load into 
.br
\fIuser\fP Username to load data for 
.RE
.PP
\fBReturns\fP
.RS 4
bool True if load successful
.RE
.PP
\fBParameters\fP
.RS 4
\fIdata\fP \fBSave\fP structure to load data into 
.br
\fIuser\fP Username to load data for 
.RE
.PP
\fBReturns\fP
.RS 4
bool True if load successful 
.RE
.PP

.PP
Definition at line \fB18\fP of file \fBSaveGame\&.cpp\fP\&.
.SS "bool SaveGame::save (const \fBSave\fP & data, const string & user)\fR [static]\fP"

.PP
\fBSave\fP current game data\&. \fBSave\fP current game state for user\&.

.PP
\fBParameters\fP
.RS 4
\fIdata\fP \fBSave\fP structure containing data to save 
.br
\fIuser\fP Username to save data for 
.RE
.PP
\fBReturns\fP
.RS 4
bool True if save successful
.RE
.PP
\fBParameters\fP
.RS 4
\fIdata\fP \fBSave\fP structure containing data 
.br
\fIuser\fP Username to save data for 
.RE
.PP
\fBReturns\fP
.RS 4
bool True if save successful 
.RE
.PP

.PP
Definition at line \fB33\fP of file \fBSaveGame\&.cpp\fP\&.
.SS "bool SaveGame::valid (const string & user)\fR [static]\fP"

.PP
Check if save data exists for user\&. Validate username format\&.

.PP
\fBParameters\fP
.RS 4
\fIuser\fP Username to check 
.RE
.PP
\fBReturns\fP
.RS 4
bool True if save data exists
.RE
.PP
\fBParameters\fP
.RS 4
\fIuser\fP Username to validate 
.RE
.PP
\fBReturns\fP
.RS 4
bool True if username is valid
.RE
.PP
Username must be 3-30 characters, alphanumeric or underscore 
.PP
Definition at line \fB48\fP of file \fBSaveGame\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Blackjack_1 from the source code\&.
