.TH "Stats" 3 "Blackjack_1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stats \- Simple structure holding game statistics\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <PlayerStats\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBgames\fP"
.br
.ti -1c
.RI "int \fBwins\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Simple structure holding game statistics\&. 
.PP
Definition at line \fB49\fP of file \fBPlayerStats\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Stats::games"
Total games played 
.PP
Definition at line \fB50\fP of file \fBPlayerStats\&.h\fP\&.
.SS "int Stats::wins"
Total games won 
.PP
Definition at line \fB51\fP of file \fBPlayerStats\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Blackjack_1 from the source code\&.
